version: "3.4"

services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - ./postgres.env
    volumes:
      - "pg:/var/lib/postgresql/data"

  chainlink:
    image: "smartcontract/chainlink"
    env_file:
      - ./chainlink.env
    ports: 
      - "5100:5100"
    links:
      - "postgres"
    volumes:
      - .:/host

volumes:
  pg:
